version: "3"
services:
  db:
    image: postgres:10
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - DATABASE_HOST=localhost
      - TZ=Asia/Tokyo
    volumes:
      - ./init:/docker-entrypoint-initdb.d